spring:
  application:
    name: finch-kotlin

  # Database 설정
  datasource:
    url: "${DB_URL}"
    username: "${DB_NAME}"
    password: "${DB_PWD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # Mail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 개발 환경에서는 false, 운영 환경에서는 true

server:
  port: 8080

cors:
  origin:
    local: "${CORS_ORIGIN_LOCAL}"
    development: "${CORS_ORIGIN_DEVELOPMENT}"
    production: "${CORS_ORIGIN_PRODUCTION}"

jwt:
  secret: "${JWT_SECRET}"
  access-token-expiration: "${JWT_ACCESS_EXPIRATION}"
  refresh-token-expiration: "${JWT_REFRESH_EXPIRATION}"