spring:
  application:
    name: finch-kotlin

  # Database 설정
  datasource:
    url: "${DB_URL}"
    username: "${DB_NAME}"
    password: "${DB_PWD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            redirect-uri: "${GOOGLE_REDIRECT_URL}"
            scope: email, profile
            authorization-grant-type: authorization_code

server:
  port: 8080

cors:
  origin:
    local: "${CORS_ORIGIN_LOCAL}"
    development: "${CORS_ORIGIN_DEVELOPMENT}"
    production: "${CORS_ORIGIN_PRODUCTION}"

jwt:
  secret: "${JWT_SECRET}"
  access-token-expiration: "${JWT_ACCESS_EXPIRATION}"
  refresh-token-expiration: "${JWT_REFRESH_EXPIRATION}"